[package]
name = "trace_tools"
version = "0.1.0"
edition = "2021"
authors = ["TimWood"]
license = "MIT OR Apache-2.0"
description = "Memory tracking and visualization tools for Rust applications."

[dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "tracing-log"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
svg = "0.18.0"
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1.0"
backtrace = { version = "0.3", features = ["serde"], optional = true }

[lib]
name = "trace_tools"
path = "src/lib.rs"

[features]
backtrace = ["dep:backtrace"]
tracking-allocator = []
default = ["tracking-allocator"]
test = []

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
crossbeam = "0.8"
rayon = "1.7"
parking_lot = "0.12"
tracing-test = "0.2"
tempfile = "3.10.1" # Or a compatible version


[[example]]
name = "lifecycles"
path = "examples/lifecycles.rs"