[package]
name = "trace_tools"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "tracing-log"], optional = true } # Made optional
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
svg = "0.18.0"
chrono = { version = "0.4", features = ["serde"] }
crossbeam = "0.8"
thiserror = "2.0.12"
lazy_static = "1.4.0"
backtrace = { version = "0.3", features = ["serde"], optional = true }
tokio = { version = "1.0", features = ["full"] } # Restored with full features
inferno = "0.11.19" # Removed features = ["flamegraph"]
rustc-demangle = "0.1" # Corrected: hyphen instead of underscore
treemap = "0.3.2"     # Changed to an older, available version
scopeguard = "1.2.0"  # For RAII-style guards

[lib]
name = "trace_tools"
path = "src/lib.rs"

[features]
backtrace = ["dep:backtrace"]
tracking-allocator = []
default = ["tracking-allocator"] # enable-subscriber is opt-in
enable-subscriber = ["dep:tracing-subscriber"]
test = []

[dev-dependencies]
tracing-test = "0.2"
tempfile = "3.10.1" # Or a compatible version


[[example]]
name = "lifecycles"
path = "examples/lifecycles.rs"

[[bin]]
name = "lifecycle_validation_test_executable"
path = "tests/lifecycle_validation_test.rs"